# Generated by Django 3.2.5 on 2021-07-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
                ('area_code', models.CharField(max_length=10)),
                ('total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'summary',
                'unique_together': {('last_update', 'area_code')},
            },
        ),
        migrations.CreateModel(
            name='DaillyPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('area_code', models.CharField(max_length=10)),
                ('patients', models.BigIntegerField()),
            ],
            options={
                'db_table': 'dailly_patients',
                'unique_together': {('target_date', 'area_code')},
            },
        ),
    ]
